export const defaultData = [
    {
        category: "Entertainment: Music",
        type: "multiple",
        difficulty: "easy",
        question: "In the  Rossini opera, what was the name of &#039;The Barber of Seville&#039;?",
        correct_answer: "Figaro",
        incorrect_answers: [
            "Angelo",
            "Fernando",
            "Dave",
        ],
    },
    {
        category: "Entertainment: Video Games",
        type: "multiple",
        difficulty: "easy",
        question: "What ingredient is NOT used to craft a cake in Minecraft?",
        correct_answer: "Bread",
        incorrect_answers: [
            "Wheat",
            "Milk",
            "Egg",
        ],
    },
    {
        category: "Science: Gadgets",
        type: "multiple",
        difficulty: "easy",
        question: "The term &quot;battery&quot; to describe an electrical storage device was coined by?",
        correct_answer: "Benjamin Franklin",
        incorrect_answers: [
            "Nikola Tesla",
            "Luigi Galvani",
            " Alessandro Volta",
        ],
    },
    {
        category: "Entertainment: Video Games",
        type: "multiple",
        difficulty: "easy",
        question: "In Portal 2, how did CEO of Aperture Science, Cave Johnson, presumably die?",
        correct_answer: "Moon Rock Poisoning",
        incorrect_answers: [
            "Accidentally sending a portal to the Moon",
            "Slipped in the shower",
            "Asbestos Poisoning",
        ],
    },
    {
        category: "Entertainment: Video Games",
        type: "multiple",
        difficulty: "easy",
        question: "Who is the founder of Team Fortress 2&#039;s fictional company &quot;Mann Co&quot;?",
        correct_answer: "Zepheniah Mann",
        incorrect_answers: [
            "Cave Johnson",
            "Wallace Breem",
            "Saxton Hale",
        ],
    },
    {
        category: "Entertainment: Board Games",
        type: "multiple",
        difficulty: "easy",
        question: "Which one of these is not a real game in the Dungeons &amp; Dragons series?",
        correct_answer: "Extreme Dungeons &amp; Dragons",
        incorrect_answers: [
            "Advanced Dungeons &amp; Dragons",
            "Dungeons &amp; Dragons 3.5th edition",
            "Advanced Dungeons &amp; Dragons 2nd edition",
        ],
    },
    {
        category: "Entertainment: Film",
        type: "multiple",
        difficulty: "easy",
        question: "At the end of the 2001 film &quot;Rat Race&quot;, whose concert do the contestants crash?",
        correct_answer: "Smash Mouth",
        incorrect_answers: [
            "Bowling for Soup",
            "Sum 41",
            "Linkin Park",
        ],
    },
    {
        category: "Entertainment: Video Games",
        type: "multiple",
        difficulty: "easy",
        question: "Which of the following characters from the game &quot;Overwatch&quot; was revealed to be homosexual in December of 2016?",
        correct_answer: "Tracer",
        incorrect_answers: [
            "Widowmaker",
            "Sombra",
            "Symmetra",
        ],
    },
    {
        category: "Entertainment: Books",
        type: "multiple",
        difficulty: "easy",
        question: "What is the name of Sherlock Holmes&#039;s brother?",
        correct_answer: "Mycroft Holmes",
        incorrect_answers: [
            "Mederi Holmes",
            "Martin Holmes",
            "Herbie Hancock Holmes",
        ],
    },
    {
        category: "Entertainment: Music",
        type: "multiple",
        difficulty: "easy",
        question: "What 1970&#039;s American ballad referred to the 1959 plane crash as the &quot;the day the music died&quot;?",
        correct_answer: "American Pie",
        incorrect_answers: [
            "Kentucky Rain",
            "I Will Always Love You",
            "Rock &#039;n&#039; Roll Suicide",
        ],
    },
]